version: '3.8'

services:
  # 1. VERİTABANI (SQL Server)
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: chatapp_sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd!
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  # 2. REDIS (Mesajlaşma ve RSA anahtarları için kritik)
  redis:
    image: redis:latest
    container_name: chatapp_redis
    ports:
      - "6379:6379"

  # 3. BACKEND (C# API)
  api:
    build: 
      context: . # Backend klasörünün içinde olduğu için nokta koyuyoruz
      dockerfile: Dockerfile # Projenin içinde bir Dockerfile olmalı
    container_name: chatapp_api
    ports:
      - "7220:8080"
    depends_on:
      - db
      - redis
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=ChatAppDb;User Id=sa;Password=YourStrong@Passw0rd!;TrustServerCertificate=True;
      - Configuration__Redis=redis:6379 

volumes:
  sql_data: